spring.profiles.include=common
server.port=${SERVER_PORT:8082}
spring.application.name=smart-pantry-yemeksepeti-service
marketplace.mg.enabled=false
marketplace.ys.enabled=true

daily.product.details.scheduler.migros.enabled=false
daily.product.details.scheduler.yemeksepeti.enabled=true

docs.title=Smart Pantry - Yemeksepeti Service API
docs.description=Only Yemeksepeti microservice endpoints
docs.servers=http://localhost:8080/ys|Gateway Yemeksepeti;http://localhost:8080/mg|Gateway Migros
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
