import java.io.BufferedWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class GenerateHistoryRangeSql {

    private static final LocalDate START_DATE = LocalDate.of(2026, 1, 24);
    private static final LocalDate END_DATE = LocalDate.of(2026, 2, 24);
    private static final String DEFAULT_OUTPUT_FILE = "seed_price_history_2026_01_24_2026_02_24.sql";
    private static final DateTimeFormatter SQL_TIMESTAMP = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private record Mapping(long marketplaceProductId, long productId, String marketplace, BigDecimal price) {
    }

    public static void main(String[] args) throws Exception {
        String dbUrl = System.getenv("DB_URL");
        String dbUser = System.getenv("DB_USERNAME");
        String dbPassword = System.getenv("DB_PASSWORD");
        String outputFile = System.getenv("OUT_FILE");
        if (isBlank(outputFile)) {
            outputFile = DEFAULT_OUTPUT_FILE;
        }
        if (isBlank(dbUrl) || isBlank(dbUser)) {
            throw new IllegalStateException("DB_URL and DB_USERNAME must be set.");
        }

        try (Connection connection = DriverManager.getConnection(dbUrl, dbUser, dbPassword)) {
            List<Mapping> mappings = loadMappings(connection);
            if (mappings.isEmpty()) {
                System.out.println("No mappings found in price_history. SQL file was not created.");
                return;
            }

            int statementCount = writeSqlFile(outputFile, mappings);
            System.out.println("SQL file created: " + outputFile);
            System.out.println("Mapped marketplace products: " + mappings.size());
            System.out.println("Generated insert statements: " + statementCount);
            System.out.println("Date range: " + START_DATE + " to " + END_DATE);
        }
    }

    private static List<Mapping> loadMappings(Connection connection) throws SQLException {
        String sql = """
                select distinct on (ph.marketplace_product_id)
                       ph.marketplace_product_id,
                       ph.product_id,
                       ph.marketplace,
                       ph.price
                from price_history ph
                order by ph.marketplace_product_id, ph.recorded_at desc
                """;

        List<Mapping> mappings = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {
            while (rs.next()) {
                mappings.add(new Mapping(
                        rs.getLong("marketplace_product_id"),
                        rs.getLong("product_id"),
                        rs.getString("marketplace"),
                        rs.getBigDecimal("price")
                ));
            }
        }
        return mappings;
    }

    private static int writeSqlFile(String outputFile, List<Mapping> mappings) throws IOException {
        int count = 0;
        try (BufferedWriter writer = java.nio.file.Files.newBufferedWriter(java.nio.file.Path.of(outputFile))) {
            writer.write("-- Generated by scripts/GenerateHistoryRangeSql.java");
            writer.newLine();
            writer.write("-- Date range: 2026-01-24 to 2026-02-24");
            writer.newLine();
            writer.write("begin;");
            writer.newLine();
            writer.newLine();

            for (Mapping mapping : mappings) {
                LocalDate day = START_DATE;
                while (!day.isAfter(END_DATE)) {
                    LocalDateTime recordedAt = day.atTime(10, 0);
                    writer.write(buildInsertSql(mapping, recordedAt));
                    writer.newLine();
                    count++;
                    day = day.plusDays(1);
                }
                writer.newLine();
            }

            writer.write("commit;");
            writer.newLine();
        }
        return count;
    }

    private static String buildInsertSql(Mapping mapping, LocalDateTime recordedAt) {
        String timestamp = recordedAt.format(SQL_TIMESTAMP);
        String marketplace = escapeSql(mapping.marketplace());
        String price = mapping.price().setScale(2, RoundingMode.HALF_UP).toPlainString();

        return "insert into price_history (marketplace, product_id, marketplace_product_id, price, recorded_at) " +
                "select '" + marketplace + "', " + mapping.productId() + ", " + mapping.marketplaceProductId() + ", " + price + ", '" + timestamp + "' " +
                "where not exists (" +
                "select 1 from price_history " +
                "where marketplace_product_id = " + mapping.marketplaceProductId() +
                " and recorded_at = '" + timestamp + "'" +
                ");";
    }

    private static String escapeSql(String value) {
        return value == null ? "" : value.replace("'", "''");
    }

    private static boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }
}
